"""create_users_table

Revision ID: 42a34a405c0b
Revises: 
Create Date: 2026-03-04 17:54:34.674712

"""
from typing import Sequence, Union
from uuid import UUID
from datetime import datetime, timezone
import bcrypt

from alembic import op
import sqlalchemy as sa
from src.app.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '42a34a405c0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def hash_password(password: str) -> str:
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed.decode('utf-8')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('ADMIN', 'USER', name='userrole')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_with_salt', sa.String(length=255), nullable=False),
    sa.Column('role', user_role_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###

    # Seed Root User
    root_id = UUID('00000000-0000-0000-0000-000000000000')
    hashed_password = hash_password(settings.ROOT_USER_PASSWORD)
    
    op.execute(
        sa.text(
            "INSERT INTO users (id, username, password_with_salt, role, created_at, created_by) "
            "VALUES (:id, :username, :password, CAST(:role AS userrole), :created_at, :created_by)"
        ).bindparams(
            id=root_id,
            username=settings.ROOT_USER_NAME,
            password=hashed_password,
            role='ADMIN',
            created_at=datetime.now(timezone.utc),
            created_by=root_id
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    sa.Enum(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
